### PR TITLE
Avoid multiple downloads in stack-to-nix

### PR DESCRIPTION
**Pull request by hamishmack**
This change avoids downloading the files multiple times (once for each subdirectory).

### CODE REVIEW

**Review by rvl — APPROVED** [review]
Sweet! I do not have time at the moment to thoroughly review or test, but adding the cabal subdir seems correct.

While you have the bonnet up, is #68 something that could be fixed here?

**Comment by michaelpj** [comment]
Can we use the same trick for cabal projects? They often have the same issue.

**Comment by hamishmack** [comment]
> While you have the bonnet up, is input-output-hk/haskell.nix#1686 something that could be fixed here?

I have added a partial fix for this.  If one of the `.nix` files is missing it will now download the source and regenerate them.  This is not ideal, a better fix might be to write a `nix-prefetch-git` that allows the user to specify the actual `sha256` (not just the expected one).

> Can we use the same trick for cabal projects? They often have the same issue.

`plan-to-nix` does not have have code like this, but I'll have a look at the way `stackProject` and `cabalProject` use `builtins.fetchGit`.  I imagine we are calling it once for each subdir (and unlike when we use `pkgs.fetchgit`) that will probably cause multiple downloads.

**Comment by michaelpj** [comment]
> plan-to-nix does not have have code like this, but I'll have a look at the way stackProject and cabalProject use builtins.fetchGit. 

Ah okay, I was actually confused and I was thinking about that code indeed.

**Comment by rvl** [comment]
> I have added a partial fix for this. If one of the .nix files is missing it will now download the source and regenerate them.

Thanks, this is ideal for me - fixes the vast majority of cases.

**Comment by hasufell** [comment]
Great addition. I also stumbled over this recently, because my internet connection is rather slow right now. Would be good if this can move forward somehow.

**Pull request merged**
