### PR TITLE
Add support for the new LTS formats.

### PR DESCRIPTION
**Pull request by angerman**
Stackage did change the lts formats. They are now at https://github.com/commercialhaskell/stackage-snapshots. Both the nightly as well as lts. The format change required some change int he `lts2plan` function. As the new snapshots doesn't list the libraries shipped with ghc anymore we needed to graft them back in. This also means that the new stackage-snapshots won't list those packages in the package set, as they did before.

### CODE REVIEW

**Comment by qrilka** [comment]
Internally Stack uses https://github.com/commercialhaskell/stackage-content/blob/master/stack/global-hints.yaml to get GHC boot libraries.

**Comment by angerman** [comment]
> Internally Stack uses https://github.com/commercialhaskell/stackage-content/blob/master/stack/global-hints.yaml to get GHC boot libraries.

Ohh neat! Thank's @qrilka, guess that makes my package-versions script superfulous.

**Comment by qrilka** [comment]
At the same time it is an internal implementation detail and a fallback in case when GHC is not installed and the list can't be retrieved from the actual compiler.

**Comment by serras** [comment]
@angerman thanks very much, I have been waiting for this. I'm happy to help with my limited knowledge :)

**Comment by angerman** [comment]
> At the same time it is an internal implementation detail and a fallback in case when GHC is not installed and the list can't be retrieved from the actual compiler.

@qrilka fair. I'll take my chances, eventually I'll have to resurrect the pkg generator.

**Pull request merged**
